+incdir+$ZRISC_ROOT/src/rtl
$ZRISC_ROOT/src/rtl/zrisc_alu_main.sv
$ZRISC_ROOT/src/rtl/zrisc_btb.sv
$ZRISC_ROOT/src/rtl/zrisc_cache_fsm.sv
$ZRISC_ROOT/src/rtl/zrisc_cache.sv
$ZRISC_ROOT/src/rtl/zrisc_cache_tag_ram.sv
$ZRISC_ROOT/src/rtl/zrisc_core.sv
$ZRISC_ROOT/src/rtl/zrisc_cp15_cb.sv
$ZRISC_ROOT/src/rtl/zrisc_dcache_fsm.sv
$ZRISC_ROOT/src/rtl/zrisc_dcache.sv
$ZRISC_ROOT/src/rtl/zrisc_decode_main.sv
$ZRISC_ROOT/src/rtl/zrisc_decode.sv
$ZRISC_ROOT/src/rtl/zrisc_decompile.sv
$ZRISC_ROOT/src/rtl/zrisc_dual_rank_synchronizer.sv
$ZRISC_ROOT/src/rtl/zrisc_fetch_main.sv
$ZRISC_ROOT/src/rtl/zrisc_fifo.sv
$ZRISC_ROOT/src/rtl/zrisc_issue_main.sv
$ZRISC_ROOT/src/rtl/zrisc_mem_inv_block.sv
$ZRISC_ROOT/src/rtl/zrisc_memory_main.sv
$ZRISC_ROOT/src/rtl/zrisc_mode16_decoder_main.sv
$ZRISC_ROOT/src/rtl/zrisc_mode16_decoder.sv
$ZRISC_ROOT/src/rtl/zrisc_postalu_main.sv
$ZRISC_ROOT/src/rtl/zrisc_predecode_coproc.sv
$ZRISC_ROOT/src/rtl/zrisc_predecode_main.sv
$ZRISC_ROOT/src/rtl/zrisc_predecode_uop_sequencer.sv
$ZRISC_ROOT/src/rtl/zrisc_ram_simple_ben.sv
$ZRISC_ROOT/src/rtl/zrisc_ram_simple_nopipe.sv
$ZRISC_ROOT/src/rtl/zrisc_ram_simple.sv
$ZRISC_ROOT/src/rtl/zrisc_register_file.sv
$ZRISC_ROOT/src/rtl/zrisc_shifter_main.sv
$ZRISC_ROOT/src/rtl/zrisc_shifter_multiply.sv
$ZRISC_ROOT/src/rtl/zrisc_shifter_shift.sv
$ZRISC_ROOT/src/rtl/zrisc_sync_fifo.sv
$ZRISC_ROOT/src/rtl/zrisc_tlb_check.sv
$ZRISC_ROOT/src/rtl/zrisc_tlb_fsm.sv
$ZRISC_ROOT/src/rtl/zrisc_tlb.sv
$ZRISC_ROOT/src/rtl/zrisc_top.sv
$ZRISC_ROOT/src/rtl/zrisc_wb_merger.sv
$ZRISC_ROOT/src/rtl/zrisc_writeback.sv
