#!/usr/bin/perl -w
die "Error: Verilator not found on your system. Exiting." if system("verilator --version");
$x = `verilator --version`;
$x =~ m/Verilator (.*?) .*$/;
print "Got version $1\n";

if ( $1 < 4 ) {
        die "Error: Unsupported verilator version.";
} else {
        print "Verilator version IS supported.\n";
}

exit 0;
